import {
    Alignment,
    Autoformat,
    BlockQuote,
    Bold,
    ClassicEditor as ClassicEditorBase,
    Code,
    CodeBlock,
    Essentials,
    FindAndReplace,
    Font,
    Heading,
    HeadingButtonsUI,
    HeadingOption,
    Image,
    ImageCaption,
    ImageInsert,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    Italic,
    Link,
    List,
    MediaEmbed,
    Paragraph,
    ParagraphButtonUI,
    PasteFromOffice,
    PictureEditing,
    SimpleUploadAdapter,
    Strikethrough,
    Table,
    TableToolbar,
    TextTransformation,
    Underline,
    WordCount,
} from 'ckeditor5';

// There is an import css issue here
// https://github.com/ckeditor/ckeditor5/issues/16638
import './../../../node_modules/ckeditor5/dist/ckeditor5.css';
// Override the default styles.
import './custom.css';

class ClassicEditor extends ClassicEditorBase {}

ClassicEditor.builtinPlugins = [
    Essentials,
    Autoformat,
    Bold,
    Italic,
    BlockQuote,
    Heading,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    Link,
    List,
    MediaEmbed,
    Paragraph,
    PasteFromOffice,
    PictureEditing,
    Table,
    TableToolbar,
    TextTransformation,
    HeadingButtonsUI,
    ParagraphButtonUI,
    IndentBlock,
    Code,
    Alignment,
    ImageResize,
    CodeBlock,
    Underline,
    Strikethrough,
    WordCount,
    ImageInsert,
    Font,
    FindAndReplace,
    SimpleUploadAdapter,
];

ClassicEditor.defaultConfig = {
    toolbar: {
        items: [
            'paragraph',
            'heading2',
            'heading3',
            '|',
            'fontSize',
            'bold',
            'italic',
            'underline',
            'strikethrough',
            'code',
            '|',
            'bulletedList',
            'numberedList',
            '|',
            'alignment',
            '|',
            'indent',
            'outdent',
            '-',
            'link',
            'blockQuote',
            'imageInsert',
            'insertTable',
            'mediaEmbed',
            'codeBlock',
            '|',
            'findAndReplace',
        ],
        shouldNotGroupWhenFull: true,
    },
    heading: {
        options: [
            {
                model: 'paragraph',
                title: 'Paragraph',
                class: 'ck-heading_paragraph',
            },
            {
                model: 'heading2',
                view: 'h2',
                title: 'Heading 2',
                class: 'ck-heading_heading2',
            },
            {
                model: 'heading3',
                view: 'h3',
                title: 'Heading 3',
                class: 'ck-heading_heading3',
            },
        ] as HeadingOption[],
    },
    fontSize: {
        options: ['tiny', 'default', 'big'],
    },
    link: {
        addTargetToExternalLinks: true,
    },
    image: {
        toolbar: ['toggleImageCaption', 'imageTextAlternative'],
    },
    table: {
        contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells'],
    },
    codeBlock: {
        languages: [
            { language: 'text', label: 'Plain text' }, // The default language.
            { language: 'bash', label: 'Bash' },
            { language: 'c', label: 'C' },
            { language: 'cs', label: 'C#' },
            { language: 'cpp', label: 'C++' },
            { language: 'css', label: 'CSS' },
            { language: 'dart', label: 'Dart' },
            { language: 'dockerfile', label: 'Dockerfile' },
            { language: 'go', label: 'Go' },
            { language: 'hcl', label: 'HCL' },
            { language: 'html', label: 'HTML' },
            { language: 'ini', label: 'INI' },
            { language: 'java', label: 'Java' },
            { language: 'javascript', label: 'JavaScript' },
            { language: 'json', label: 'JSON' },
            { language: 'kotlin', label: 'Kotlin' },
            { language: 'nginx', label: 'Nginx Config' },
            { language: 'php', label: 'PHP' },
            { language: 'python', label: 'Python' },
            { language: 'ruby', label: 'Ruby' },
            { language: 'rust', label: 'Rust' },
            { language: 'shell', label: 'Shell' },
            { language: 'sql', label: 'SQL' },
            { language: 'swift', label: 'Swift' },
            { language: 'toml', label: 'TOML' },
            { language: 'typescript', label: 'TypeScript' },
            { language: 'xml', label: 'XML' },
            { language: 'yaml', label: 'YAML' },
        ],
        indentSequence: '    ',
    },
    language: 'en',
};

declare global {
    interface Window {
        ClassicEditor: typeof ClassicEditor;
    }
}

window.ClassicEditor = ClassicEditor;
